apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: folding-at-home1
  name: folding-at-home1
  namespace: folding
spec:
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: folding-at-home1
  template:
    metadata:
      labels:
        app: folding-at-home1
      name: folding-at-home1
    spec:
      containers:
      - args:
        - --gpu=false
        - --smp=true
        - --team=253130
        image: covperc/fah:7.5.1
        imagePullPolicy: IfNotPresent
        name: folding
        # ports:
        # - containerPort: 7396
        #   hostPort: 7396
        #   name: http
        #   protocol: TCP
        resources:
           limits:
             memory: 750Mi
             cpu: 1.5
           requests:
             memory: 750Mi
             cpu: 1.5
        volumeMounts:
          - mountPath: /work/
            name: work
          - mountPath: /logs/
            name: logs
      hostNetwork: true
      hostPID: true
      restartPolicy: Always
      volumes:
        - hostPath:
            path: /work1/
            type: DirectoryOrCreate
          name: work
        - hostPath:
            path: /logs1/
            type: DirectoryOrCreate
          name: logs
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 10%
    type: RollingUpdate
