FROM arm32v5/debian:buster AS builder
ARG VERSION

RUN apt-get update && \
    apt-get install -y ca-certificates curl jq \
    && apt-get clean && rm -rf /var/lib/apt/lists/*


RUN curl -LO "https://dl.k8s.io/release/$VERSION/bin/linux/arm/kubectl"
