FROM debian:buster-slim@sha256:91ab14f34a8d19482248d592c0411c1611d5df4bb2b85d2a71d3758b0b05ac6d AS builder
ARG VERSION

RUN apt-get update && \
    apt-get install -y ca-certificates curl jq \
    && apt-get clean && rm -rf /var/lib/apt/lists/*


RUN curl -LO "https://dl.k8s.io/release/$VERSION/bin/linux/arm64/kubectl"
