{
 "title": "VMHub5 Exporter Dashboard",
 "tags": [
  "vmhub5",
  "exporter"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Prometheus Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "PON Access",
   "type": "stat",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "hub5_pon_status_access_allowed" }
   ]
  },
  {
   "title": "Firewall Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "hub5_pon_status_firewall" }
   ]
  },
  {
   "title": "Voip Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "hub5_pon_status_ip_voip" }
   ]
  },
  {
   "title": "IP Data Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "hub5_pon_status_ip_data" }
   ]
  },
  {
   "title": "PON Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "hub5_pon_status_up_time", "legendFormat": "Uptime" }
   ]
  },
  {
   "title": "DSLite Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hub5_provisioning_dsLite_enable"
    }
   ]
  },
  {
   "title": "IPv4 Lease and Expiry Times",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hub5_provisioning_ipv4_lease_time",
     "legendFormat": "Lease Time"
    },
    {
     "expr": "hub5_provisioning_ipv4_expire_time",
     "legendFormat": "Expire Time"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Transceiver Metrics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "targets": [
    {
     "expr": "round(hub5_pon_interface_transceiver_voltage,20)",
     "legendFormat": "Voltage"
    }
   ]
  },
  {
   "title": "Transceiver Metrics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "targets": [
    {
     "expr": "round(avg_over_time(hub5_pon_interface_laser_bias_current[5m]), 50)",
     "legendFormat": "Laser Bias Current"
    }
   ]
  },
  {
   "title": "Optical Levels",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "expr": "hub5_pon_interface_transmit_optical_level",
     "legendFormat": "Transmit Optical Level"
    },
    {
     "expr": "-hub5_pon_interface_optical_signal_level",
     "legendFormat": "Optical Signal Level"
    }
   ]
  },
  {
   "title": "Transceiver Temperature",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "hub5_pon_interface_transceiver_temp",
     "legendFormat": "Temperature"
    }
   ]
  }
 ]
}