name: Build Image

on:
  workflow_dispatch:
    inputs:
      image-name:
        description: "Image/Dir to build"
        type: string
        required: true
      push:
        description: "Push or Not the image"
        type: boolean
        default: false
        required: true

  workflow_call:
    inputs:
      image-name:
        description: "Image/Dir to build"
        type: string
        required: true
      push:
        description: "Push or Not the image"
        type: boolean
        default: false
        required: true
    secrets:
      DOCKERHUB_USERNAME:
        required: true
        description: Docker hub username
      DOCKERHUB_TOKEN:
        required: true
        description: Docker hub Token

jobs:
  build_images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Metadata
        id: set_meta
        working-directory: "./${{ inputs.image-name }}/"
        run: |
          pwd
          echo VERSION=$(cat VERSION) >> $GITHUB_OUTPUT
          if [ -e PLATFORMS ]; then
            echo PLATFORMS=$(cat PLATFORMS | tr '\n' ',' ) >> $GITHUB_OUTPUT
          else
            echo "PLATFORMS=" >> $GITHUB_OUTPUT
          fi

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ inputs.image-name }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Needed as part of https://github.com/docker/buildx/issues/495#issuecomment-1043341496
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v3
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: ${{steps.set_meta.outputs.PLATFORMS}}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: "${{inputs.image-name}}/"
          push: ${{inputs.push}}
          pull: true
          build-args: VERSION=${{steps.set_meta.outputs.VERSION}}
          platforms: ${{steps.set_meta.outputs.PLATFORMS}}
          tags: |
            ghcr.io/davidcollom/${{inputs.image-name}}:${{steps.set_meta.outputs.VERSION}}
            ${{ secrets.DOCKERHUB_USERNAME }}/${{inputs.image-name}}:${{steps.set_meta.outputs.VERSION}}
          cache-from: type=gha
          cache-to: type=gha,mode=max
