name: Build Image

on:
  workflow_dispatch:
    inputs:
      image_name:
        required: true
        type: string

  # workflow_call:
  #   inputs:
  #     image_name:
  #       required: true
  #       type: string

jobs:
  build_container_images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Metadata
        id: set_meta
        working-directory: ${{ inputs.image_name }}/
        run: |
          echo VERSION=$(cat VERSION) >> $GITHUB_OUTPUT
          if [ -e PLATFORMS ];
            echo PLATFORMS=$(tr '\m' ',' PLATFORMS) >> $GITHUB_OUTPUT
          else
            echo "PLATFORMS=" >> $GITHUB_OUTPUT
          fi

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          platforms: ${{steps.set_meta.outputs.PLATFORMS}}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:mysubdir"
          push: true
          tags:  ${{ secrets.DOCKERHUB_USERNAME }}/${{input.image_name}}:${{steps.set_meta.outputs.VERSION}}
